services:
  osm-import-rust:
    image: osm-import-rust:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: osm-import-rust
    restart: unless-stopped
    environment:
      - SERVER_PORT=8080
      - RUST_LOG=info
    volumes:
      - ./data:/app/data
    ports:
      - "8080:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
